name: 'openhealthdash'
version: '1.0.0'
config-version: 2

profile: 'openhealthdash'

model-paths: ["dbt/models"]
seed-paths: ["dbt/seeds"]
test-paths: ["dbt/tests"]
analysis-paths: ["dbt/analyses"]
macro-paths: ["dbt/macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  openhealthdash:
    staging:
      +materialized: view
    marts:
      +materialized: table